### ISSUE TITLE
Ninja scans dependencies before order-only dependencies are run

### ISSUE THREAD

**Issue by mathstuf** [ninja-build/ninja#760]
There is a [CMake bug](http://www.cmake.org/Bug/view.php?id=14747) about ninja not running this properly:

``` ninja
rule R
    command = $COMMAND
build always: R
    COMMAND = echo 1 >> out
build out: phony out
build out-copy: R out || always
    COMMAND = cp out out-copy
build all: phony out-copy always
default all
```

Basically, ninja is scanning the dependencies of `out-copy` before `always` is run and therefore skips the fact that `out` has changed. Is it intended that dependency scanning is only guaranteed to be done after direct dependencies, not order-only dependencies or a bug? If the former, documentation that this is the case would be nice.

**Comment by ahartmetz** [comment]
Is anybody still interested in implementing Brad's suggestion?
I use CMake with Ninja, I find the byproducts thing to be a bit of a bummer because it's hard to explain to people who just want to build something without becoming an expert in build system matters, and I enjoy working on graph algorithms. If nobody else picks this up, I'll add it to the pile of stuff I want to do in "my copious free time" :blush:.

**Comment by arjanhouben** [comment]
I think this bug should be given more attention, as builds can very easily be incorrect without the user knowing it.
I use a lot of the following constructs.
```
add_custom_target(
   generate_version
    COMMAND
    <generate version.tmp>
    copy_if_different version.tmp version.h
)
add_executable( my_exe main.cpp version.h )
target_link_libraries( my_exe some_lib )
add_dependencies( my_exe generate_version )
```
This is an oversimplified example, leaving out the GENERATED property for the **version.h** file for example.
The problem here is that while **my_exe** will probably build without issues, if the only thing to change is the contents of **version.h**, **my_exe** will not be updated.
This _may_ be obvious enough since the build step will be pretty much instant. 
However, as in my case often is, if **some_lib** is updated which should lead to a different **version.h**, **my_exe** is NOT updated, since the only thing to happen is to re-link the executable.
Another problem with this, is that it is non-trivial to check afterwards, as the timestamps of **version.h**, **some_lib** and **my_exe** _might_ actually be exactly as you expect, while still not having included the latest content of **version.h** in **my_exe**!

**Comment by mathstuf** [comment]
FYI, the better way to do that is `add_custom_command(OUTPUT version.h)` followed by `add_custom_target(generate_version DEPENDS version.h)`. The dependencies actually work that way.

**Comment by arjanhouben** [comment]
That would not have the same effect, as version.h is not generated if it already exists. The point of the generate_version command is to run always and check for reasons to bump the version, but only trigger a new build if something actually did change.

**Comment by mathstuf** [comment]
Oh, right. Add `version.h.noexist` to the output list. I'll find the code which does this properly later today…

**Comment by bradking** [comment]
In the time since this issue was reported I've become very familiar with Ninja internals while implementing [features needed for Fortran support](https://groups.google.com/forum/#!topic/ninja-build/tPOcu5EWXio).  It is pretty clear that what is requested in this issue cannot be implemented without a major re-implementation of Ninja internals.  It just does not fit in Ninja's model.  Furthermore, deferred stat prevents a monolithic build plan from being computed ahead of time, so progress information cannot be generated reliably.  The feature's I've implemented to support Fortran (not yet integrated upstream) do allow build-time dependency discovery in the rare cases that really need it.

Since CMake 3.2 both the [add_custom_command](https://cmake.org/cmake/help/v3.6/command/add_custom_command.html) and [add_custom_target](https://cmake.org/cmake/help/v3.6/command/add_custom_target.html) commands support a `BYPRODUCTS` option meant specifically to add the extra dependency information that is needed to generate a proper `build.ninja` file without requiring changes to Ninja.  With a mature solution on the CMake side, I think this issue can be closed.

**Comment by arjanhouben** [comment]
I have been able to create a sample which shows how this solution does not work for RC files.
[CMakeLists.txt](https://github.com/ninja-build/ninja/files/529095/CMakeLists.txt)
[generate_version.cmake.txt](https://github.com/ninja-build/ninja/files/529098/generate_version.cmake.txt) ( remove .txt )

If you run 
`cmake -GNinja <source_dir>;ninja`
it will complain that it cannot find generate_version.rc
run ninja again and it will work ( because the last run actually did create them )

if you do the same with NMake
`cmake -G"NMake Makefiles" <source_dir>;nmake`
it will complain that it cannot generate version.cpp

removing the byproducts and instead adding them as outputs for a custom target make the sample work as expected on NMake.
But that is not a solution for Ninja as it doesn't update the files before compiling/linking, leading to a generated executable that is one iteration behind the generated source files.

Not that you can check the validity of the build by comparing the contents of version.cpp, the output of the generate_test executable and the version info ( on windows ) of the executable, for example through sigcheck.exe

**Comment by bradking** [comment]
@arjanhouben you're missing a dependency:

```cmake
add_dependencies(generate_test generate_version_files)
```

**Comment by arjanhouben** [comment]
you are right, that will fix the first time missing file dependency.
It doesn't fix the problem unfortunately, as can be seen:
```
cmake ...
ninja
./generate_test.exe -> YkJ3PdwtuK
sigcheck.exe generate_test.exe -> YkJ3PdwtuK
```
so far so good, now I run (only) Ninja again
```
ninja
./generate_test.exe -> Mss8Ib8WNg
sigcheck.exe generate_test.exe -> YkJ3PdwtuK
```
Now it is clear that the RC file was NOT used in the binary ( same string as before ) while the version.cpp WAS updated ( new string in executable )
Note that the RC file itself was updated, it just was not used in the creation of the new binary

**Comment by bradking** [comment]
@arjanhouben I can't reproduce that.  It works for me.  Either way, this discussion is outside the scope of this issue so if you still have trouble please ask over in CMake land.

**Comment by nico** [comment]
Oh sorry, looks like the earlier parts of the issue are still valid.

**Comment by bradking** [comment]
>  looks like the earlier parts of the issue are still valid.

@nico technically yes, but as I noted [here](https://github.com/ninja-build/ninja/issues/760#issuecomment-243425513) solving this will require a fundamental shift in Ninja's model.  Unless that is ever a realistic option I don't think there is a reason to keep this open.  We now have a mature solution on the CMake side for the original problem that motivated this issue.

**Comment by arjanhouben** [comment]
I've created a CMake issue for the out of date RC file here: https://gitlab.kitware.com/cmake/cmake/issues/16417
As @bradking pointed out, it does not seem to be an issue in Ninja, but it is most easily reproduced by using Ninja as a generator
